[package]
name = "jalm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cron = "0.12"
chrono = "0.4"
clap = { version = "4.0", features = ["derive"] }
colored = "2.0"
